### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by tanmayac** [kubiko/opengrok-snap#2]
How do I use opengrok.deploy to deploy a different webapp. The "-c" option is picked up but not source_war and target_war. A bit of investigation suggests that we need to set the configuration / env variable WEBAPP_NAME. How do I do that ?

**Comment by kubiko** [comment]
Hi @tanmayac 
you can run `$ opengrok.help` to see options to configure
For your case, you can configure it by calling:
`$ snap set opengrok.webapp-name=<webapp name>`
then just re-deploy

**Comment by tanmayac** [comment]
Thanks !

**Comment by kubiko** [comment]
@tanmayac happy to close the issue?

**Comment by tanmayac** [comment]
How do index code code at a location like "/workspace" ? I get errors like ERROR: Source root /workspace/src/ must be a directory.   ?

**Comment by kubiko** [comment]
@tanmayac sorry I have missed this one
So problem would be likely with permissions. opengrok inside snap runs fully confined and sandboxed, thin like app on the phone. As such it does not have access to the most of the system.
As such any attempt to access `/workspace` would be blocked.
Work around this, you will need to create dir in 
`/var/snap/opengrok/common/` e.g. `/var/snap/opengrok/common/workspace`
then set bind mount from `/workspace` to `/var/snap/opengrok/common/workspace`
Now you can should be able to set src and data as
`$ snap set opengrok opengrok.src-data=/var/snap/opengrok/common/workspace/data`
`$ snap set opengrok opengrok.src-root=/var/snap/opengrok/common/workspace/src`

Side note, if your workspace would be on removable storage, then you do not need to this, if you connect `removable-media` interface, snap has access to `/mnt` directory
